optim: Adam
optim_args:
  lr: 1.e-3
  betas: [0.9, 0.999]
  eps: 1.e-8
  weight_decay: 0
scheduler: ReduceLROnPlateau
scheduler_type: step
scheduler_args:
  factor: 0.1
  patience: 2000
  threshold: 1.e-4
  threshold_mode: rel
  min_lr: 1.e-5
