dataset: ImageNet
epochs: 350
arch: efficientnet-b3
batch_size: 16384
optim: RMSpropTF
optim_args:
    lr: 1.024
    momentum: 0.9
    alpha: 0.9
    eps: 1.e-3
scheduler: StepLR
scheduler_args:
    step_size: 187
    gamma: 0.97
scheduler_type: iteration
scheduler_warmup: 390
autoaugment: True
random_crop: True
random_horizontal_flip: True
color_jitter: True
lighting: True
label_smoothing: 0.1
l2_regularization: 1.e-5
model_ema_decay: 0.9999
criteria_name: train_acc_1
checkpoint_criteria: [0.3, 0.5, 0.7, 0.73, 0.75, 0.76, 0.77, 0.78, 0.79, 0.80]
