dataset: ImageNet
epochs: 90
arch: ResNet18
batch_size: 16384
optim: SGD
optim_args:
    lr: 0.4
    momentum: 0.99
    nesterov: True
scheduler: LinearDecay
scheduler_args:
  decay_factor: 3.e-3
  decay_steps: 6.5e+3
  warmup_steps: 390
scheduler_type: iteration
random_resized_crop: True
random_horizontal_flip: True
label_smoothing: 0.1
l2_regularization: 1.e-4
criteria_name: train_acc_1
checkpoint_criteria: [0.3, 0.4, 0.5, 0.6, 0.65, 0.66, 0.67, 0.68, 0.69, 0.70]
