dataset: ImageNet
epochs: 90
arch: ResNet50
batch_size: 8192
optim: SGD
optim_args:
    lr: 0.2
    momentum: 0.99
    nesterov: True
scheduler: LinearDecay
scheduler_args:
  decay_factor: 3.e-3
  decay_steps: 1.3e+4
  warmup_steps: 780
scheduler_type: iteration
random_resized_crop: True
random_horizontal_flip: True
label_smoothing: 0.1
l2_regularization: 1.e-4
criteria_name: train_acc_1
checkpoint_criteria: [0.3, 0.5, 0.7, 0.73, 0.75, 0.76, 0.77, 0.78, 0.79, 0.80]
