dataset: ImageNet
epochs: 120
batch_size: 1024
arch: vgg11_bn
arch_args:
  num_classes: 1000
optim: SGD
optim_args:
    lr: 0.00125
    momentum: 0.99
    nesterov: True
scheduler: LinearDecay
scheduler_args:
  decay_factor: 3.e-3
  decay_steps: 1.36e+5
  warmup_steps: 6240
scheduler_type: iteration
random_resized_crop: True
random_horizontal_flip: True
l2_regularization: 1.e-4
criteria_name: train_acc_1
checkpoint_criteria: [0.2, 0.3, 0.4, 0.5, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6]
