dataset: ImageNet
epochs: 120
batch_size: 4096
arch: vgg19_bn
arch_args:
  num_classes: 1000
optim: SGD
optim_args:
    lr: 0.005
    momentum: 0.99
    nesterov: True
scheduler: LinearDecay
scheduler_args:
  decay_factor: 3.e-3
  decay_steps: 3.4e+4
  warmup_steps: 1560
scheduler_type: iteration
random_resized_crop: True
random_horizontal_flip: True
l2_regularization: 1.e-4
criteria_name: train_acc_1
checkpoint_criteria: [0.2, 0.3, 0.4, 0.5, 0.6, 0.64, 0.65, 0.66, 0.67, 0.68]
