dataset: MNIST
epochs: 400
batch_size: 1024
arch: SmallFullyConnected
arch_args:
  num_classes: 10
optim: SGD
optim_args:
    lr: 1.e-3
    momentum: 0.9
checkpoint_criteria: [2.0, 1.75, 1.5, 1.25, 1.0, 0.75, 0.50, 0.25, 0.1, 0.05, 0.025, 0.01]
criteria_name: train_loss
